pipeline {
    agent any

    options {
  buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '5', numToKeepStr: '5')
    }


    stages {
        stage('Hello1') {
            steps {
                echo 'Hello World'
            }
        }



        stage('Hello2') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }

        stage('Hello3') {
            steps {
                echo 'Hello World'
            }
        }
    }
}